name: alice_lightweight
description: Lightweight Alice version. Removed additional dependencies except dio.
version: 3.11.0
homepage: https://github.com/jhomlala/alice

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.8.0+1
  rxdart: ^0.28.0
  share_plus: ^12.0.0
  path_provider: ^2.1.5
  http: ^1.4.0